# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_pytorchlearn',
                'doc_host': 'https://anujk3.github.io',
                'git_url': 'https://github.com/anujk3/nbdev_pytorchlearn',
                'lib_path': 'nbdev_pytorchlearn'},
  'syms': { 'nbdev_pytorchlearn.core': {'nbdev_pytorchlearn.core.say_hello': ('core.html#say_hello', 'nbdev_pytorchlearn/core.py')},
            'nbdev_pytorchlearn.pytorch_basics': { 'nbdev_pytorchlearn.pytorch_basics.hello_world': ( 'pytorchbasics.html#hello_world',
                                                                                                      'nbdev_pytorchlearn/pytorch_basics.py')}}}
