# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_pytorchbasics.ipynb.

# %% auto 0
__all__ = ['hello_world']

# %% ../nbs/01_pytorchbasics.ipynb 4
def hello_world():
    print("Hello World!!!")

# %% ../nbs/01_pytorchbasics.ipynb 5
hello_world()
